--- 
title: "River Valley Connectivity Project"
author: "Brendan Casey"
supervisor: "Catherine Shier"
site: bookdown::bookdown_site
output: 
    bookdown::gitbook:
      split_by: "section"
      split_bib: no
   
    
      
bibliography: references/library.bib
citation-style: references/nature.csl
documentclass: book
link-citations: true
github-repo: https://github.com/bgcasey/RV_connectivity
description: "This is document walks through the project workflow."


---

# Project Overview

```{r GlobalOptions, echo=FALSE}
options(bookdown.render.file_scope = FALSE, knitr.duplicate.label = "allow") 
knitr::opts_chunk$set(cache.path = "5_cache/")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```

## Project plan {-}

```{r child = '0_documentation/project_plan.md'}
```




## Workflow overview {-}
```{r child = '2_code/rNotebooks/workflow_overview.Rmd'}
```

## Data sources {-}
```{r child = '2_code/rNotebooks/dataSources.Rmd'}
```

# Prepare data

## Circuitscape {-}

```{r child = '2_code/rNotebooks/prep_circuitscape.Rmd'}
```

##  Biophysical data {-}

```{r child = '2_code/rNotebooks/prep_spatialCovariates.Rmd'}
```

# Calculate Metrics

## Overlay {-}

```{r child = '2_code/rNotebooks/overlayAnalysis.Rmd'}
```

## Proximity {-}

```{r child = '2_code/rNotebooks/proximityAnalysis.Rmd'}
```

## Raster {-}

```{r child = '2_code/rNotebooks/rasterAnalysis.Rmd'}
```

## Combine {-}
```{r child = '2_code/rNotebooks/combineMetrics.Rmd'}
```


# Compare Pinchpoints 

## Principal Componants Analysis {-}

# Multivariate maps

```{r child = '2_code/rNotebooks/visualizeResults.Rmd'}
```

## Profile plots {-}

```{r child ='2_code/rNotebooks/crossSection.Rmd'}
```


# Weighted overlay model

# Management recommendations


# References


<div id="refs"></div>



# Appendix
