
```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```



```{r eval=FALSE}
library(raster)
```


### Load data {-}


#### Rasters {-}

Load prepared rasters.

```{r eval=FALSE}
load("1_data/manual/slope.rData")
load("1_data/manual/aspect.rData")
load("1_data/manual/SlopeRange.rData")
```



#### Pinch-points {-}

Load buffered pinch-point polygons

```{r eval=FALSE}

# buffered pinch point polygons
"3_pipeline/store/pp_s_clip_clus_buf_ext.rData"

# study area
load("1_data/manual/study_area.rdata")

# load clipped road data
load("1_data/manual/v_road_clip.rdata")

# load polygon representing North Central Region of Saskatchewan region of the ribbon of green
load("1_data/manual/nscr.rdata")  
```


### Prepare rasters {-}
 
Stack rasters into a single object


### Extract data {-}

Extract and summarize raster data within each pinch-point polygon

### Clean summary dataframe {-}